// Auto-generated by tools/build_portal_assets.py. Do not edit manually.
const BOOK_REFS = {
  "accumulators": [
    {
      "title": "4.5.1 Obtaining data from executors with accumulators",
      "page": 125,
      "score": 0.266
    }
  ],
  "actions": [],
  "amazon-ec2-deployment": [
    {
      "title": "11.6 Running on Amazon EC2",
      "page": 350,
      "score": 0.456
    },
    {
      "title": "11.6.2 Creating an EC2 standalone cluster",
      "page": 352,
      "score": 0.268
    },
    {
      "title": "11.6.3 Using the EC2 cluster",
      "page": 354,
      "score": 0.259
    }
  ],
  "astar-search-algorithm": [
    {
      "title": "9.3 Implementing the A* search algorithm",
      "page": 297,
      "score": 0.445
    },
    {
      "title": "9.3.1 Understanding the A* algorithm",
      "page": 298,
      "score": 0.325
    },
    {
      "title": "9.2.2 Shortest-paths algorithm",
      "page": 292,
      "score": 0.322
    }
  ],
  "broadcast-variables": [
    {
      "title": "3.2.6 Broadcast variables",
      "page": 83,
      "score": 0.596
    },
    {
      "title": "4.5.2 Sending data to executors using broadcast variables",
      "page": 127,
      "score": 0.393
    },
    {
      "title": "4.5 Using accumulators and broadcast variables to communicate with Spark executors",
      "page": 125,
      "score": 0.358
    }
  ],
  "catalyst-optimizer": [
    {
      "title": "5.5 Catalyst optimizer",
      "page": 170,
      "score": 0.775
    },
    {
      "title": "7.7.2 LBFGS optimizer",
      "page": 244,
      "score": 0.384
    }
  ],
  "cluster-web-ui": [
    {
      "title": "11.3 Standalone cluster web UI",
      "page": 343,
      "score": 0.584
    },
    {
      "title": "10.4 Spark web UI",
      "page": 325,
      "score": 0.495
    },
    {
      "title": "12.2.3 Mesos web UI",
      "page": 379,
      "score": 0.415
    }
  ],
  "configuring-spark": [
    {
      "title": "10.3 Configuring Spark",
      "page": 323,
      "score": 0.518
    },
    {
      "title": "Downloading, installing, and configuring Spark",
      "page": 439,
      "score": 0.405
    },
    {
      "title": "12.1.5 Configuring Spark on YARN",
      "page": 366,
      "score": 0.403
    }
  ],
  "connected-components": [
    {
      "title": "9.2.4 Connected components",
      "page": 294,
      "score": 0.597
    },
    {
      "title": "9.2.5 Strongly connected components",
      "page": 296,
      "score": 0.512
    },
    {
      "title": "1.2 Spark components",
      "page": 36,
      "score": 0.375
    }
  ],
  "cross-validation": [
    {
      "title": "7.6.6 K-fold cross-validation",
      "page": 241,
      "score": 0.497
    },
    {
      "title": "8.2.5 Performing k-fold cross-validation",
      "page": 262,
      "score": 0.401
    }
  ],
  "d3js-visualization": [],
  "data-partitioning": [
    {
      "title": "4.2 Understanding data partitioning and reducing data shuffling",
      "page": 102,
      "score": 0.371
    },
    {
      "title": "4.2.4 Mapping data in partitions",
      "page": 109,
      "score": 0.348
    },
    {
      "title": "4.2.1 Using Spark’s data partitioners",
      "page": 102,
      "score": 0.317
    }
  ],
  "dataframes": [
    {
      "title": "5.1 Working with DataFrames",
      "page": 134,
      "score": 0.373
    },
    {
      "title": "5.1.5 Converting DataFrames to RDDs",
      "page": 152,
      "score": 0.341
    },
    {
      "title": "5.1.1 Creating DataFrames from RDDs",
      "page": 136,
      "score": 0.316
    }
  ],
  "datasets": [
    {
      "title": "5.2 Beyond DataFrames: introducing DataSets",
      "page": 157,
      "score": 0.253
    }
  ],
  "decision-trees": [
    {
      "title": "8.3.1 Decision trees",
      "page": 267,
      "score": 0.586
    },
    {
      "title": "8.3 Decision trees and random forests",
      "page": 266,
      "score": 0.437
    }
  ],
  "deep-learning-concepts": [
    {
      "title": "Chapter 14: Deep learning on Spark with H2O",
      "page": 411,
      "score": 0.408
    },
    {
      "title": "14.1 What is deep learning?",
      "page": 412,
      "score": 0.397
    },
    {
      "title": "14.3.3 Building and evaluating a deep-learning model using the Sparkling Water API",
      "page": 426,
      "score": 0.317
    }
  ],
  "discretized-streams-dstreams": [
    {
      "title": "6.1.4 Using discretized streams",
      "page": 180,
      "score": 0.491
    },
    {
      "title": "6.1.3 Creating a discretized stream",
      "page": 178,
      "score": 0.317
    }
  ],
  "double-rdd-functions": [
    {
      "title": "2.4 Double RDD functions",
      "page": 64,
      "score": 0.727
    },
    {
      "title": "2.4.1 Basic statistics with double RDD functions",
      "page": 65,
      "score": 0.508
    },
    {
      "title": "4.1.2 Basic pair RDD functions",
      "page": 96,
      "score": 0.418
    }
  ],
  "feature-scaling": [
    {
      "title": "7.4.6 Feature scaling and mean normalization",
      "page": 230,
      "score": 0.421
    }
  ],
  "filtering-and-aggregating": [
    {
      "title": "3.2.4 Aggregating the data",
      "page": 80,
      "score": 0.323
    }
  ],
  "graphx-api": [
    {
      "title": "1.2.5 Spark GraphX",
      "page": 38,
      "score": 0.375
    },
    {
      "title": "9.1.1 Constructing graphs using GraphX API",
      "page": 284,
      "score": 0.326
    }
  ],
  "grouping-and-sorting": [
    {
      "title": "4.3 Joining, sorting, and grouping data",
      "page": 110,
      "score": 0.393
    },
    {
      "title": "4.3.3 Grouping data",
      "page": 119,
      "score": 0.371
    },
    {
      "title": "5.1.6 Grouping and joining data",
      "page": 153,
      "score": 0.354
    }
  ],
  "h2o-framework": [
    {
      "title": "14.2 Using H2O with Spark",
      "page": 413,
      "score": 0.33
    },
    {
      "title": "14.4.4 Stopping the H2O cluster",
      "page": 434,
      "score": 0.262
    },
    {
      "title": "14.3.1 Loading data into an H2O frame",
      "page": 419,
      "score": 0.253
    }
  ],
  "hive-metastore": [
    {
      "title": "5.3.1 Table catalog and Hive metastore",
      "page": 159,
      "score": 0.429
    }
  ],
  "job-and-resource-scheduling": [
    {
      "title": "10.2 Job and resource scheduling",
      "page": 317,
      "score": 0.729
    },
    {
      "title": "10.2.2 Spark job scheduling",
      "page": 318,
      "score": 0.51
    },
    {
      "title": "12.2.4 Mesos resource scheduling",
      "page": 381,
      "score": 0.472
    }
  ],
  "joining-data": [
    {
      "title": "4.3.1 Joining data",
      "page": 110,
      "score": 0.58
    },
    {
      "title": "5.1.6 Grouping and joining data",
      "page": 153,
      "score": 0.47
    },
    {
      "title": "4.3 Joining, sorting, and grouping data",
      "page": 110,
      "score": 0.418
    }
  ],
  "kafka-integration": [
    {
      "title": "6.2.1 Setting up Kafka",
      "page": 194,
      "score": 0.251
    }
  ],
  "kmeans-clustering": [
    {
      "title": "8.4.1 K-means clustering",
      "page": 275,
      "score": 0.394
    },
    {
      "title": "8.4 Using k-means clustering",
      "page": 274,
      "score": 0.364
    },
    {
      "title": "Chapter 8: ML: classification and clustering",
      "page": 246,
      "score": 0.26
    }
  ],
  "linear-algebra": [
    {
      "title": "7.2 Linear algebra in Spark",
      "page": 215,
      "score": 0.596
    },
    {
      "title": "appendix C: A primer on linear algebra",
      "page": 446,
      "score": 0.435
    },
    {
      "title": "7.3 Linear regression",
      "page": 221,
      "score": 0.329
    }
  ],
  "linear-regression": [
    {
      "title": "7.3 Linear regression",
      "page": 221,
      "score": 0.649
    },
    {
      "title": "7.7 Optimizing linear regression",
      "page": 242,
      "score": 0.598
    },
    {
      "title": "7.3.1 About linear regression",
      "page": 221,
      "score": 0.515
    }
  ],
  "loading-json": [
    {
      "title": "3.2.2 Loading JSON",
      "page": 76,
      "score": 0.655
    },
    {
      "title": "5.4.3 Loading data",
      "page": 169,
      "score": 0.338
    },
    {
      "title": "7.5.4 Loading and saving the model",
      "page": 233,
      "score": 0.296
    }
  ],
  "logistic-regression": [
    {
      "title": "8.2 Logistic regression",
      "page": 249,
      "score": 0.651
    },
    {
      "title": "8.2.6 Multiclass logistic regression",
      "page": 264,
      "score": 0.503
    },
    {
      "title": "8.2.1 Binary logistic regression model",
      "page": 250,
      "score": 0.461
    }
  ],
  "mapreduce-shortcomings": [
    {
      "title": "1.1.2 MapReduce’s shortcomings",
      "page": 33,
      "score": 0.592
    }
  ],
  "mean-normalization": [
    {
      "title": "7.4.6 Feature scaling and mean normalization",
      "page": 230,
      "score": 0.439
    }
  ],
  "mesos-architecture": [
    {
      "title": "12.2.1 Mesos architecture",
      "page": 374,
      "score": 0.589
    },
    {
      "title": "12.1.1 YARN architecture",
      "page": 360,
      "score": 0.385
    },
    {
      "title": "12.2 Running Spark on Mesos",
      "page": 373,
      "score": 0.293
    }
  ],
  "mesos-resource-scheduling": [
    {
      "title": "12.2.4 Mesos resource scheduling",
      "page": 381,
      "score": 0.674
    },
    {
      "title": "10.2 Job and resource scheduling",
      "page": 317,
      "score": 0.484
    },
    {
      "title": "10.2.1 Cluster resource scheduling",
      "page": 318,
      "score": 0.472
    }
  ],
  "ml-basics": [
    {
      "title": "5.1.2 DataFrame API basics",
      "page": 143,
      "score": 0.319
    },
    {
      "title": "8.1.2 ML parameters",
      "page": 248,
      "score": 0.294
    },
    {
      "title": "8.1 Spark ML library",
      "page": 247,
      "score": 0.286
    }
  ],
  "optimization": [],
  "pagerank": [
    {
      "title": "9.2.3 Page rank",
      "page": 293,
      "score": 0.254
    }
  ],
  "pair-rdds": [
    {
      "title": "4.1.1 Creating pair RDDs",
      "page": 95,
      "score": 0.516
    },
    {
      "title": "4.1 Working with pair RDDs",
      "page": 95,
      "score": 0.479
    },
    {
      "title": "4.2.3 Repartitioning RDDs",
      "page": 108,
      "score": 0.323
    }
  ],
  "pre-distributed": [
    {
      "title": "7.2.2 Distributed matrices",
      "page": 220,
      "score": 0.376
    },
    {
      "title": "2.2.3 The notion of a resilient distributed dataset",
      "page": 55,
      "score": 0.293
    }
  ],
  "pre-formats": [],
  "pre-functional": [],
  "pre-hdfs": [],
  "pre-sparksession": [],
  "random-forests": [
    {
      "title": "8.3.2 Random forests",
      "page": 272,
      "score": 0.586
    },
    {
      "title": "8.3 Decision trees and random forests",
      "page": 266,
      "score": 0.437
    }
  ],
  "rdd-lineage-and-dag": [
    {
      "title": "4.4.3 Saving the RDD lineage with checkpointing",
      "page": 125,
      "score": 0.4
    },
    {
      "title": "4.4.1 RDD dependencies and Spark execution",
      "page": 122,
      "score": 0.286
    },
    {
      "title": "4.4 Understanding RDD dependencies",
      "page": 122,
      "score": 0.25
    }
  ],
  "rdds": [
    {
      "title": "4.1.1 Creating pair RDDs",
      "page": 95,
      "score": 0.301
    },
    {
      "title": "4.2.3 Repartitioning RDDs",
      "page": 108,
      "score": 0.299
    },
    {
      "title": "5.1.5 Converting DataFrames to RDDs",
      "page": 152,
      "score": 0.281
    }
  ],
  "realtime-dashboard-architecture": [
    {
      "title": "12.1.1 YARN architecture",
      "page": 360,
      "score": 0.35
    },
    {
      "title": "12.2.1 Mesos architecture",
      "page": 374,
      "score": 0.339
    },
    {
      "title": "10.1 An overview of Spark’s runtime architecture",
      "page": 314,
      "score": 0.27
    }
  ],
  "regression-and-classification-with-deep-learning": [
    {
      "title": "14.4 Performing classification with H2O’s deep learning",
      "page": 430,
      "score": 0.475
    },
    {
      "title": "14.3 Performing regression with H2O’s deep learning",
      "page": 419,
      "score": 0.446
    },
    {
      "title": "7.1.2 Classification of machine-learning algorithms",
      "page": 212,
      "score": 0.378
    }
  ],
  "regularization": [
    {
      "title": "7.6.5 Avoiding overfitting by using regularization",
      "page": 240,
      "score": 0.297
    }
  ],
  "running-applications": [
    {
      "title": "11.4.4 Killing applications",
      "page": 348,
      "score": 0.438
    },
    {
      "title": "Chapter 3: Writing Spark applications",
      "page": 68,
      "score": 0.357
    },
    {
      "title": "6.1 Writing Spark Streaming applications",
      "page": 176,
      "score": 0.35
    }
  ],
  "running-spark-with-docker": [
    {
      "title": "12.2.6 Running Spark with Docker",
      "page": 384,
      "score": 0.487
    }
  ],
  "saving-computation-state": [
    {
      "title": "6.1.7 Saving the computation state over time",
      "page": 183,
      "score": 0.538
    },
    {
      "title": "5.4.2 Saving data",
      "page": 167,
      "score": 0.297
    },
    {
      "title": "6.1.6 Starting and stopping the streaming computation",
      "page": 182,
      "score": 0.284
    }
  ],
  "shortest-paths": [
    {
      "title": "9.2.2 Shortest-paths algorithm",
      "page": 292,
      "score": 0.528
    }
  ],
  "shuffling": [
    {
      "title": "4.2.2 Understanding and avoiding unnecessary shuffling",
      "page": 104,
      "score": 0.276
    }
  ],
  "spark-cluster-types": [
    {
      "title": "10.1.2 Spark cluster types",
      "page": 316,
      "score": 0.591
    },
    {
      "title": "11.2.2 Starting the cluster manually",
      "page": 340,
      "score": 0.323
    },
    {
      "title": "10.5.2 Local cluster mode",
      "page": 333,
      "score": 0.312
    }
  ],
  "spark-components": [
    {
      "title": "1.2 Spark components",
      "page": 36,
      "score": 0.522
    },
    {
      "title": "10.1.1 Spark runtime components",
      "page": 314,
      "score": 0.438
    },
    {
      "title": "9.2.4 Connected components",
      "page": 294,
      "score": 0.361
    }
  ],
  "spark-ecosystem": [
    {
      "title": "1.4 Spark ecosystem",
      "page": 41,
      "score": 0.521
    }
  ],
  "spark-history-server": [
    {
      "title": "11.5 Spark History Server and event logging",
      "page": 349,
      "score": 0.459
    },
    {
      "title": "5.3.3 Connecting to Spark SQL through the Thrift server",
      "page": 162,
      "score": 0.28
    }
  ],
  "spark-ide-project-setup": [
    {
      "title": "13.3.3 The WebStatsDashboard project",
      "page": 409,
      "score": 0.307
    },
    {
      "title": "13.3.1 The KafkaLogsSimulator project",
      "page": 402,
      "score": 0.279
    },
    {
      "title": "13.3.2 The StreamingLogAnalyzer project",
      "page": 402,
      "score": 0.276
    }
  ],
  "spark-ml-library": [
    {
      "title": "8.1 Spark ML library",
      "page": 247,
      "score": 0.647
    },
    {
      "title": "8.1.2 ML parameters",
      "page": 248,
      "score": 0.305
    },
    {
      "title": "8.1.3 ML pipelines",
      "page": 249,
      "score": 0.293
    }
  ],
  "spark-revolution": [
    {
      "title": "1.1.1 The Spark revolution",
      "page": 33,
      "score": 0.645
    }
  ],
  "spark-runtime-architecture": [
    {
      "title": "10.1 An overview of Spark’s runtime architecture",
      "page": 314,
      "score": 0.476
    },
    {
      "title": "12.1.1 YARN architecture",
      "page": 360,
      "score": 0.39
    },
    {
      "title": "10.1.1 Spark runtime components",
      "page": 314,
      "score": 0.37
    }
  ],
  "spark-shell": [
    {
      "title": "2.2.1 Starting the Spark shell",
      "page": 51,
      "score": 0.402
    },
    {
      "title": "11.2.1 Starting the cluster with shell scripts",
      "page": 337,
      "score": 0.266
    },
    {
      "title": "2.2 Using Spark shell and writing your first Spark program",
      "page": 51,
      "score": 0.255
    }
  ],
  "spark-stages-and-tasks": [
    {
      "title": "4.4.2 Spark stages and tasks",
      "page": 124,
      "score": 0.675
    },
    {
      "title": "10.4.2 Stages page",
      "page": 328,
      "score": 0.318
    }
  ],
  "spark-streaming-components": [
    {
      "title": "1.2 Spark components",
      "page": 36,
      "score": 0.411
    },
    {
      "title": "10.1.1 Spark runtime components",
      "page": 314,
      "score": 0.397
    },
    {
      "title": "1.2.3 Spark Streaming",
      "page": 38,
      "score": 0.39
    }
  ],
  "spark-submit": [
    {
      "title": "3.3.3 Using spark-submit",
      "page": 90,
      "score": 0.608
    }
  ],
  "spark-vm-setup": [
    {
      "title": "2.1 Using the spark-in-action VM",
      "page": 47,
      "score": 0.287
    }
  ],
  "spark-web-ui": [
    {
      "title": "10.4 Spark web UI",
      "page": 325,
      "score": 0.632
    },
    {
      "title": "12.2.3 Mesos web UI",
      "page": 379,
      "score": 0.459
    },
    {
      "title": "11.3 Standalone cluster web UI",
      "page": 343,
      "score": 0.419
    }
  ],
  "spark_hands_on_setup_guide": [],
  "sparkling-water-api": [
    {
      "title": "14.2.2 Starting Sparkling Water on Spark",
      "page": 414,
      "score": 0.524
    },
    {
      "title": "14.4.3 Building the model with the Sparkling Water API",
      "page": 434,
      "score": 0.424
    },
    {
      "title": "14.3.3 Building and evaluating a deep-learning model using the Sparkling Water API",
      "page": 426,
      "score": 0.341
    }
  ],
  "sql-queries": [
    {
      "title": "5.3.2 Executing SQL queries",
      "page": 161,
      "score": 0.475
    },
    {
      "title": "Chapter 5: Sparkling queries with Spark SQL",
      "page": 133,
      "score": 0.413
    },
    {
      "title": "1.2.2 Spark SQL",
      "page": 37,
      "score": 0.325
    }
  ],
  "standalone-cluster-components": [
    {
      "title": "11.1 Spark standalone cluster components",
      "page": 335,
      "score": 0.71
    },
    {
      "title": "11.2 Starting the standalone cluster",
      "page": 336,
      "score": 0.438
    },
    {
      "title": "Chapter 11: Running on a Spark standalone cluster",
      "page": 334,
      "score": 0.435
    }
  ],
  "streaming-performance-tuning": [
    {
      "title": "6.3 Performance of Spark Streaming jobs",
      "page": 200,
      "score": 0.427
    },
    {
      "title": "6.3.1 Obtaining good performance",
      "page": 201,
      "score": 0.315
    },
    {
      "title": "1.2.3 Spark Streaming",
      "page": 38,
      "score": 0.297
    }
  ],
  "transformations": [
    {
      "title": "2.3.2 Using the distinct and flatMap transformations",
      "page": 58,
      "score": 0.342
    },
    {
      "title": "2.3 Basic RDD actions and transformations",
      "page": 56,
      "score": 0.309
    }
  ],
  "transforming-joining-graphs": [
    {
      "title": "9.1.2 Transforming graphs",
      "page": 285,
      "score": 0.513
    },
    {
      "title": "7.4.4 Transforming to labeled points",
      "page": 229,
      "score": 0.322
    },
    {
      "title": "5.1.6 Grouping and joining data",
      "page": 153,
      "score": 0.303
    }
  ],
  "tungsten-performance": [
    {
      "title": "5.6 Performance improvements with Tungsten",
      "page": 172,
      "score": 0.447
    },
    {
      "title": "6.3.1 Obtaining good performance",
      "page": 201,
      "score": 0.331
    },
    {
      "title": "7.5.2 Evaluating the model’s performance",
      "page": 232,
      "score": 0.307
    }
  ],
  "uberjars": [],
  "websockets": [],
  "window-operations": [
    {
      "title": "6.1.8 Using window operations for time-limited calculations",
      "page": 190,
      "score": 0.379
    }
  ],
  "yarn-architecture": [
    {
      "title": "12.1.1 YARN architecture",
      "page": 360,
      "score": 0.662
    },
    {
      "title": "12.2.1 Mesos architecture",
      "page": 374,
      "score": 0.36
    },
    {
      "title": "12.1.7 YARN UI",
      "page": 369,
      "score": 0.302
    }
  ],
  "yarn-resource-scheduling": [
    {
      "title": "12.1.3 Resource scheduling in YARN",
      "page": 363,
      "score": 0.627
    },
    {
      "title": "10.2 Job and resource scheduling",
      "page": 317,
      "score": 0.496
    },
    {
      "title": "10.2.1 Cluster resource scheduling",
      "page": 318,
      "score": 0.475
    }
  ]
};
