import json
import re
from difflib import SequenceMatcher
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WORD_RE = re.compile(r"\b[\w']+\b")


def slug_tokens(value: str) -> set[str]:
    stop = {
        "and", "or", "the", "a", "an", "to", "of", "in", "on", "with",
        "for", "api", "spark", "apache", "using", "running",
    }
    return {t for t in re.findall(r"[a-z0-9]+", value.lower()) if t not in stop}


def js_stringify(name: str, data) -> str:
    return (
        f"// Auto-generated by tools/build_portal_assets.py. Do not edit manually.\n"
        f"const {name} = "
        + json.dumps(data, ensure_ascii=False, indent=2)
        + ";\n"
    )


def parse_answer(line: str) -> str | None:
    patterns = [
        r"\*\*Correct Answer:\*\*\s*(.+)",
        r"\*\*Answer:\*\*\s*(.+)",
        r"\*Answer:\*\s*(.+)",
        r"\*\s+\*\*Answer:\*\*\s*(.+)",
        r"\*\s+\*\*Correct Answer:\*\*\s*(.+)",
        r"-\s+\*\*Answer:\*\*\s*(.+)",
        r"-\s+\*\*Correct Answer:\*\*\s*(.+)",
        r"-\s*\*\*Answer\*\*:\s*(.+)",
        r"-\s*\*\*Answer\*\*:\s*(.+)",
        r"-\s*\*\*Answer:\*\*\s*(.+)",
        r"-\s*\*\*Correct Answer:\*\*\s*(.+)",
    ]
    for pat in patterns:
        match = re.match(pat, line.strip(), re.I)
        if match:
            return match.group(1).strip().rstrip(".")
    return None


def parse_explanation(line: str) -> str | None:
    patterns = [
        r"\*\*Mastery Explanation:\*\*\s*(.+)",
        r"\*Mastery Explanation:\s*(.+)\*",
        r"\*\s+\*\*Mastery Explanation:\*\*\s*(.+)",
        r"-\s+\*\*Mastery Explanation:\*\*\s*(.+)",
        r"-\s*\*\*Mastery Explanation\*\*:\s*(.+)",
        r"\*\*Explanation:\*\*\s*(.+)",
        r"\*\s+\*\*Explanation:\*\*\s*(.+)",
        r"-\s*\*\*Explanation\*\*:\s*(.+)",
    ]
    for pat in patterns:
        match = re.match(pat, line.strip(), re.I)
        if match:
            return match.group(1).strip().rstrip("*").strip()
    return None


def question_start(line: str):
    stripped = line.strip()
    patterns = [
        r"^\*\*Q?(\d+)\s*[:.)-]\s*(.+?)\*\*$",
        r"^\*\*Q?(\d+)\s*[:.)-]?\*\*[:\s]*(.+)",
        r"^(\d+)\.\s+\*\*(.+?)\*\*:?\s*(.*)",
    ]
    for pat in patterns:
        match = re.match(pat, stripped, re.I)
        if match:
            num = int(match.group(1))
            if len(match.groups()) == 2:
                text = match.group(2)
            else:
                text = (match.group(2) + " " + match.group(3)).strip()
            text = re.sub(r"^\s*True/False\s*:\s*", "True/False: ", text, flags=re.I)
            return num, text.strip()
    return None


def option_value(line: str) -> str | None:
    stripped = line.strip()
    match = re.match(r"^(?:[-*]\s*)?([A-Da-d])\)\s*(.+)", stripped)
    if match:
        return f"{match.group(1).upper()}) {match.group(2).strip()}"
    match = re.match(r"^[-*]\s+(True|False)\s*$", stripped, re.I)
    if match:
        return match.group(1).title()
    return None


def parse_quiz(path: Path) -> dict:
    questions = []
    current = None

    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        start = question_start(raw)
        if start:
            if current:
                questions.append(current)
            number, text = start
            current = {
                "number": number,
                "question": text,
                "options": [],
                "answer": "",
                "explanation": "",
            }
            continue

        if not current:
            continue

        answer = parse_answer(raw)
        if answer is not None:
            current["answer"] = answer
            continue

        explanation = parse_explanation(raw)
        if explanation is not None:
            current["explanation"] = explanation
            continue

        opt = option_value(raw)
        if opt:
            current["options"].append(opt)

    if current:
        questions.append(current)

    for q in questions:
        q["type"] = "true_false" if q["options"] == ["True", "False"] else "multiple_choice"
        if not q["options"] and q["answer"].lower() in {"true", "false"}:
            q["options"] = ["True", "False"]
            q["type"] = "true_false"

    return {
        "title": path.stem.replace("_quiz", "").replace("-", " ").title(),
        "questions": sorted(questions, key=lambda q: q["number"]),
    }


def best_book_refs(slug: str, entries: list[dict], limit: int = 3) -> list[dict]:
    slug_set = slug_tokens(slug)
    scored = []
    for entry in entries:
        title = entry.get("title", "")
        title_set = slug_tokens(title)
        if not title_set:
            continue
        overlap = len(slug_set & title_set) / max(1, len(slug_set | title_set))
        ratio = SequenceMatcher(None, slug.replace("-", " "), title.lower()).ratio()
        level_bonus = {4: 0.08, 3: 0.05, 2: 0.02}.get(entry.get("level"), 0)
        score = overlap * 0.75 + ratio * 0.25 + level_bonus
        if score >= 0.25:
            scored.append((score, entry))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [
        {"title": e["title"], "page": e["page"], "score": round(score, 3)}
        for score, e in scored[:limit]
    ]


def build_audit(deep_files: list[Path], quiz_data: dict, book_refs: dict) -> dict:
    deep_rows = []
    for path in deep_files:
        text = path.read_text(encoding="utf-8", errors="replace")
        deep_rows.append({
            "id": path.stem,
            "words": len(WORD_RE.findall(text)),
            "mermaidBlocks": text.count("```mermaid"),
            "bookRefCount": len(book_refs.get(path.stem, [])),
        })

    quiz_rows = []
    for slug, quiz in quiz_data.items():
        questions = quiz["questions"]
        quiz_rows.append({
            "id": slug,
            "questions": len(questions),
            "withAnswers": sum(1 for q in questions if q["answer"]),
            "withExplanations": sum(1 for q in questions if q["explanation"]),
        })

    return {
        "summary": {
            "deepDiveCount": len(deep_rows),
            "deepDivesUnder1000Words": sum(1 for r in deep_rows if r["words"] < 1000),
            "quizCount": len(quiz_rows),
            "quizzesWithFewerThan30Questions": sum(1 for r in quiz_rows if r["questions"] < 30),
            "conceptsWithoutBookRefs": sum(1 for r in deep_rows if r["bookRefCount"] == 0),
        },
        "deepDives": deep_rows,
        "quizzes": quiz_rows,
    }


def write_audit_markdown(audit: dict):
    lines = [
        "# Spark Study Portal Audit",
        "",
        "## Summary",
        "",
    ]
    for key, value in audit["summary"].items():
        lines.append(f"- **{key}:** {value}")
    lines.extend(["", "## Deep Dives Under 1000 Words", ""])
    for row in audit["deepDives"]:
        if row["words"] < 1000:
            lines.append(f"- `{row['id']}`: {row['words']} words")
    lines.extend(["", "## Quiz Files Needing Attention", ""])
    for row in audit["quizzes"]:
        if row["questions"] < 30 or row["withAnswers"] < row["questions"] or row["withExplanations"] < row["questions"]:
            lines.append(
                f"- `{row['id']}`: {row['questions']} questions, "
                f"{row['withAnswers']} answers, {row['withExplanations']} explanations"
            )
    (ROOT / "portal_audit.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    deep_files = sorted((ROOT / "Curriculum_DeepDives").glob("*.md"))
    quiz_files = sorted((ROOT / "Curriculum_Assessments").glob("*_quiz.md"))
    quiz_data = {path.stem.replace("_quiz", ""): parse_quiz(path) for path in quiz_files}

    book_entries = json.loads((ROOT / "book_index.json").read_text(encoding="utf-8"))
    book_refs = {path.stem: best_book_refs(path.stem, book_entries) for path in deep_files}

    (ROOT / "quiz_data.js").write_text(js_stringify("QUIZ_DATA", quiz_data), encoding="utf-8")
    (ROOT / "book_refs.js").write_text(js_stringify("BOOK_REFS", book_refs), encoding="utf-8")

    audit = build_audit(deep_files, quiz_data, book_refs)
    (ROOT / "portal_audit.json").write_text(json.dumps(audit, ensure_ascii=False, indent=2), encoding="utf-8")
    write_audit_markdown(audit)

    print(json.dumps(audit["summary"], indent=2))


if __name__ == "__main__":
    main()
